import Head from 'next/head'
import { Inter } from 'next/font/google'
import { HomeSlider } from '@/components/HomeSlider'
import HomeWelcomeSec from '@/components/HomeWelcomeSec/HomeWelcomeSec'
import { HomeOurRanchSec } from '@/components/HomeOurRanchSec'
import { RanchLegacySec } from '@/components/RanchLegacy'
// import { LivingRanchSec } from '@/components/LivingRanch'
import { LivingRanchSec } from '@/components/LivingRanch'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>The OLIVE ORCHARD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <HomeSlider />
        <HomeWelcomeSec />
        <HomeOurRanchSec />
        <RanchLegacySec />
        <LivingRanchSec />
      </main>
    </>
  )
}
